version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: burndb
      MYSQL_USER: burnuser
      MYSQL_PASSWORD: burnpass
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: burndb
      MYSQL_USERNAME: burnuser
      MYSQL_PASSWORD: burnpass
      SECRET_KEY: EBEFDE6593354909BD817B827D2C49E2
      AUTHHEADER_PASSWORD: 123456789
      CORS_HEADER: "*"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure