version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: burndb
      MYSQL_USER: burnuser
      MYSQL_PASSWORD: burnpass
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: burndb
      MYSQL_USERNAME: burnuser
      MYSQL_PASSWORD: burnpass
      SECRET_KEY: EBEFDE6593354909BD817B827D2C49E2
      CURRENT_DATE: '2024-12-12'
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8181:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    restart: always
