apiVersion: apps/v1
kind: Deployment
metadata:
  name: readthenburn-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readthenburn-backend
  template:
    metadata:
      labels:
        app: readthenburn-backend
    spec:
      initContainers:
        - name: init-wait
          image: alpine:3.17
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 mariadb-service 3306 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: readthenburn-backend
          image: dockr.it/goreadthenburnbackend:k8s
          env:
          - name: MYSQL_HOSTNAME
            value: mariadb-service
          - name: MYSQL_DATABASE
            value: readthenburn
          - name: MYSQL_USERNAME
            value: readthenburn
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: readthenburnmysqlpassword
                key: password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: readthenburnsecretkey
                key: password
          - name: AUTHHEADER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: readthenburnbackendauthheaderpassword
                key: password
          - name: CORS_HEADER
            value: "https://readthenburn.se"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockrit